export const cities4 = [
  {
    slug: "tokyo-osaka",
    name: "Pyongyang",
    country: "North Korea",
    countryCode: "KP",
    continent: "Asia",
    costIndex: 15,
    rentIndex: 10,
    qualityOfLife: 18,
    purchasingPower: 12,
    safety: 45,
    healthcare: 30,
    climate: 52,
    trafficCommute: 30,
    population: "3.0M",
    currency: "KPW",
    avgMonthlyCost: 400,
    image: "https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 1.5,
        "Meal for 2 (mid-range)": 6,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 0.5,
        "Imported Beer (0.33L)": 1,
        "Cappuccino": 1,
        "Coke/Pepsi (0.33L)": 0.3,
        "Water (0.33L)": 0.15,
      },
      markets: {
        "Milk (1L)": 0.4,
        "Bread (500g)": 0.2,
        "Rice (1kg)": 0.3,
        "Eggs (12)": 0.7,
        "Chicken (1kg)": 1.5,
        "Beef (1kg)": 3,
        "Apples (1kg)": 1,
        "Banana (1kg)": 0.5,
        "Tomato (1kg)": 0.3,
        "Potato (1kg)": 0.2,
        "Onion (1kg)": 0.2,
        "Water (1.5L)": 0.15,
      },
      transport: {
        "1-way Ticket (local)": 0.05,
        "Monthly Pass": 3,
        "Taxi 1km": 0.1,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 0,
        "Toyota Corolla": 0,
      },
      utilities: {
        "Basic (85m² apt)": 10,
        "Mobile Plan": 2,
        "Internet (60 Mbps)": 5,
        "Fitness Club/month": 5,
      },
      housing: {
        "1BR Center": 80,
        "1BR Outside": 40,
        "3BR Center": 180,
        "3BR Outside": 100,
        "Price/m² Center": 300,
        "Price/m² Outside": 150,
      },
      salaries: {
        "Average Net Salary": 60,
        "Mortgage Interest Rate": 5.0,
      },
    },
  },
  {
    slug: "ulaanbaatar",
    name: "Ulaanbaatar",
    country: "Mongolia",
    countryCode: "MN",
    continent: "Asia",
    costIndex: 32,
    rentIndex: 26,
    qualityOfLife: 48,
    purchasingPower: 38,
    safety: 50,
    healthcare: 50,
    climate: 28,
    trafficCommute: 30,
    population: "1.6M",
    currency: "MNT",
    avgMonthlyCost: 900,
    image: "https://images.unsplash.com/photo-1513415564510-6c78dc32f2d8?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 4,
        "Meal for 2 (mid-range)": 16,
        "McMeal at McDonald's": 5,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 3,
        "Cappuccino": 2.5,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 0.9,
        "Bread (500g)": 0.6,
        "Rice (1kg)": 0.9,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5,
        "Apples (1kg)": 2,
        "Banana (1kg)": 1.2,
        "Tomato (1kg)": 1.5,
        "Potato (1kg)": 0.6,
        "Onion (1kg)": 0.6,
        "Water (1.5L)": 0.5,
      },
      transport: {
        "1-way Ticket (local)": 0.3,
        "Monthly Pass": 12,
        "Taxi 1km": 0.4,
        "Gasoline (1L)": 1.0,
        "Volkswagen Golf": 30000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 70,
        "Mobile Plan": 8,
        "Internet (60 Mbps)": 18,
        "Fitness Club/month": 28,
      },
      housing: {
        "1BR Center": 400,
        "1BR Outside": 240,
        "3BR Center": 950,
        "3BR Outside": 550,
        "Price/m² Center": 1500,
        "Price/m² Outside": 800,
      },
      salaries: {
        "Average Net Salary": 600,
        "Mortgage Interest Rate": 16.0,
      },
    },
  },
  {
    slug: "nur-sultan",
    name: "Astana",
    country: "Kazakhstan",
    countryCode: "KZ",
    continent: "Asia",
    costIndex: 40,
    rentIndex: 34,
    qualityOfLife: 60,
    purchasingPower: 50,
    safety: 58,
    healthcare: 62,
    climate: 30,
    trafficCommute: 42,
    population: "1.2M",
    currency: "KZT",
    avgMonthlyCost: 1100,
    image: "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 5,
        "Meal for 2 (mid-range)": 20,
        "McMeal at McDonald's": 5.5,
        "Domestic Beer (0.5L)": 2,
        "Imported Beer (0.33L)": 3.5,
        "Cappuccino": 2.5,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 0.7,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.7,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 6,
        "Apples (1kg)": 0.8,
        "Banana (1kg)": 0.9,
        "Tomato (1kg)": 0.8,
        "Potato (1kg)": 0.4,
        "Onion (1kg)": 0.3,
        "Water (1.5L)": 0.4,
      },
      transport: {
        "1-way Ticket (local)": 0.3,
        "Monthly Pass": 14,
        "Taxi 1km": 0.35,
        "Gasoline (1L)": 0.5,
        "Volkswagen Golf": 24000,
        "Toyota Corolla": 19000,
      },
      utilities: {
        "Basic (85m² apt)": 65,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 12,
        "Fitness Club/month": 30,
      },
      housing: {
        "1BR Center": 500,
        "1BR Outside": 300,
        "3BR Center": 1100,
        "3BR Outside": 650,
        "Price/m² Center": 2000,
        "Price/m² Outside": 1100,
      },
      salaries: {
        "Average Net Salary": 700,
        "Mortgage Interest Rate": 14.5,
      },
    },
  },
  {
    slug: "bishkek",
    name: "Bishkek",
    country: "Kyrgyzstan",
    countryCode: "KG",
    continent: "Asia",
    costIndex: 25,
    rentIndex: 18,
    qualityOfLife: 52,
    purchasingPower: 34,
    safety: 58,
    healthcare: 52,
    climate: 55,
    trafficCommute: 35,
    population: "1.1M",
    currency: "KGS",
    avgMonthlyCost: 620,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 4,
        "Domestic Beer (0.5L)": 1,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.25,
      },
      markets: {
        "Milk (1L)": 0.6,
        "Bread (500g)": 0.3,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 0.9,
        "Chicken (1kg)": 2.5,
        "Beef (1kg)": 5,
        "Apples (1kg)": 0.7,
        "Banana (1kg)": 0.8,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.25,
        "Onion (1kg)": 0.22,
        "Water (1.5L)": 0.25,
      },
      transport: {
        "1-way Ticket (local)": 0.12,
        "Monthly Pass": 5,
        "Taxi 1km": 0.18,
        "Gasoline (1L)": 0.7,
        "Volkswagen Golf": 18000,
        "Toyota Corolla": 14000,
      },
      utilities: {
        "Basic (85m² apt)": 30,
        "Mobile Plan": 4,
        "Internet (60 Mbps)": 10,
        "Fitness Club/month": 14,
      },
      housing: {
        "1BR Center": 260,
        "1BR Outside": 150,
        "3BR Center": 580,
        "3BR Outside": 330,
        "Price/m² Center": 900,
        "Price/m² Outside": 500,
      },
      salaries: {
        "Average Net Salary": 350,
        "Mortgage Interest Rate": 18.0,
      },
    },
  },
  {
    slug: "dushanbe",
    name: "Dushanbe",
    country: "Tajikistan",
    countryCode: "TJ",
    continent: "Asia",
    costIndex: 22,
    rentIndex: 16,
    qualityOfLife: 44,
    purchasingPower: 28,
    safety: 52,
    healthcare: 42,
    climate: 62,
    trafficCommute: 28,
    population: "0.9M",
    currency: "TJS",
    avgMonthlyCost: 560,
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 3.5,
        "Domestic Beer (0.5L)": 0.8,
        "Imported Beer (0.33L)": 1.8,
        "Cappuccino": 1.2,
        "Coke/Pepsi (0.33L)": 0.4,
        "Water (0.33L)": 0.2,
      },
      markets: {
        "Milk (1L)": 0.5,
        "Bread (500g)": 0.25,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 0.9,
        "Chicken (1kg)": 2.2,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 0.6,
        "Banana (1kg)": 0.7,
        "Tomato (1kg)": 0.4,
        "Potato (1kg)": 0.22,
        "Onion (1kg)": 0.2,
        "Water (1.5L)": 0.2,
      },
      transport: {
        "1-way Ticket (local)": 0.12,
        "Monthly Pass": 5,
        "Taxi 1km": 0.15,
        "Gasoline (1L)": 0.8,
        "Volkswagen Golf": 16000,
        "Toyota Corolla": 12000,
      },
      utilities: {
        "Basic (85m² apt)": 25,
        "Mobile Plan": 3,
        "Internet (60 Mbps)": 8,
        "Fitness Club/month": 12,
      },
      housing: {
        "1BR Center": 200,
        "1BR Outside": 110,
        "3BR Center": 460,
        "3BR Outside": 260,
        "Price/m² Center": 700,
        "Price/m² Outside": 380,
      },
      salaries: {
        "Average Net Salary": 280,
        "Mortgage Interest Rate": 22.0,
      },
    },
  },
  {
    slug: "ashgabat",
    name: "Ashgabat",
    country: "Turkmenistan",
    countryCode: "TM",
    continent: "Asia",
    costIndex: 28,
    rentIndex: 20,
    qualityOfLife: 40,
    purchasingPower: 30,
    safety: 55,
    healthcare: 42,
    climate: 55,
    trafficCommute: 32,
    population: "0.8M",
    currency: "TMT",
    avgMonthlyCost: 700,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 0.8,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.4,
        "Water (0.33L)": 0.2,
      },
      markets: {
        "Milk (1L)": 0.5,
        "Bread (500g)": 0.1,
        "Rice (1kg)": 0.4,
        "Eggs (12)": 0.8,
        "Chicken (1kg)": 2,
        "Beef (1kg)": 4,
        "Apples (1kg)": 0.7,
        "Banana (1kg)": 0.8,
        "Tomato (1kg)": 0.4,
        "Potato (1kg)": 0.2,
        "Onion (1kg)": 0.18,
        "Water (1.5L)": 0.15,
      },
      transport: {
        "1-way Ticket (local)": 0.05,
        "Monthly Pass": 3,
        "Taxi 1km": 0.2,
        "Gasoline (1L)": 0.1,
        "Volkswagen Golf": 20000,
        "Toyota Corolla": 16000,
      },
      utilities: {
        "Basic (85m² apt)": 15,
        "Mobile Plan": 3,
        "Internet (60 Mbps)": 8,
        "Fitness Club/month": 10,
      },
      housing: {
        "1BR Center": 220,
        "1BR Outside": 120,
        "3BR Center": 520,
        "3BR Outside": 290,
        "Price/m² Center": 800,
        "Price/m² Outside": 420,
      },
      salaries: {
        "Average Net Salary": 320,
        "Mortgage Interest Rate": 10.0,
      },
    },
  },
  {
    slug: "thimphu",
    name: "Thimphu",
    country: "Bhutan",
    countryCode: "BT",
    continent: "Asia",
    costIndex: 30,
    rentIndex: 22,
    qualityOfLife: 65,
    purchasingPower: 38,
    safety: 72,
    healthcare: 58,
    climate: 62,
    trafficCommute: 42,
    population: "0.1M",
    currency: "BTN",
    avgMonthlyCost: 750,
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 3,
        "Cappuccino": 2,
        "Coke/Pepsi (0.33L)": 0.6,
        "Water (0.33L)": 0.3,
      },
      markets: {
        "Milk (1L)": 0.8,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 5,
        "Apples (1kg)": 1.2,
        "Banana (1kg)": 0.5,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.3,
        "Onion (1kg)": 0.3,
        "Water (1.5L)": 0.25,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 8,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 30000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 35,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 15,
        "Fitness Club/month": 18,
      },
      housing: {
        "1BR Center": 250,
        "1BR Outside": 140,
        "3BR Center": 580,
        "3BR Outside": 330,
        "Price/m² Center": 1000,
        "Price/m² Outside": 550,
      },
      salaries: {
        "Average Net Salary": 380,
        "Mortgage Interest Rate": 11.0,
      },
    },
  },
  {
    slug: "male",
    name: "Malé",
    country: "Maldives",
    countryCode: "MV",
    continent: "Asia",
    costIndex: 55,
    rentIndex: 58,
    qualityOfLife: 65,
    purchasingPower: 55,
    safety: 68,
    healthcare: 60,
    climate: 72,
    trafficCommute: 50,
    population: "0.2M",
    currency: "MVR",
    avgMonthlyCost: 1600,
    image: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 5,
        "Meal for 2 (mid-range)": 22,
        "McMeal at McDonald's": 7,
        "Domestic Beer (0.5L)": 0,
        "Imported Beer (0.33L)": 0,
        "Cappuccino": 3.5,
        "Coke/Pepsi (0.33L)": 1.2,
        "Water (0.33L)": 0.6,
      },
      markets: {
        "Milk (1L)": 2.2,
        "Bread (500g)": 1.2,
        "Rice (1kg)": 1.2,
        "Eggs (12)": 3,
        "Chicken (1kg)": 6,
        "Beef (1kg)": 10,
        "Apples (1kg)": 3.5,
        "Banana (1kg)": 1.5,
        "Tomato (1kg)": 2,
        "Potato (1kg)": 1.5,
        "Onion (1kg)": 1.2,
        "Water (1.5L)": 0.8,
      },
      transport: {
        "1-way Ticket (local)": 0.5,
        "Monthly Pass": 20,
        "Taxi 1km": 1,
        "Gasoline (1L)": 1.1,
        "Volkswagen Golf": 40000,
        "Toyota Corolla": 32000,
      },
      utilities: {
        "Basic (85m² apt)": 120,
        "Mobile Plan": 22,
        "Internet (60 Mbps)": 55,
        "Fitness Club/month": 60,
      },
      housing: {
        "1BR Center": 900,
        "1BR Outside": 600,
        "3BR Center": 2200,
        "3BR Outside": 1400,
        "Price/m² Center": 4000,
        "Price/m² Outside": 2500,
      },
      salaries: {
        "Average Net Salary": 1000,
        "Mortgage Interest Rate": 11.0,
      },
    },
  },
  {
    slug: "nay-pyi-taw",
    name: "Nay Pyi Taw",
    country: "Myanmar",
    countryCode: "MM",
    continent: "Asia",
    costIndex: 20,
    rentIndex: 15,
    qualityOfLife: 38,
    purchasingPower: 25,
    safety: 38,
    healthcare: 35,
    climate: 55,
    trafficCommute: 35,
    population: "0.9M",
    currency: "MMK",
    avgMonthlyCost: 520,
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 1.2,
        "Meal for 2 (mid-range)": 5,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.2,
        "Coke/Pepsi (0.33L)": 0.35,
        "Water (0.33L)": 0.18,
      },
      markets: {
        "Milk (1L)": 0.7,
        "Bread (500g)": 0.35,
        "Rice (1kg)": 0.3,
        "Eggs (12)": 0.8,
        "Chicken (1kg)": 1.6,
        "Beef (1kg)": 3.2,
        "Apples (1kg)": 1.4,
        "Banana (1kg)": 0.25,
        "Tomato (1kg)": 0.35,
        "Potato (1kg)": 0.28,
        "Onion (1kg)": 0.25,
        "Water (1.5L)": 0.18,
      },
      transport: {
        "1-way Ticket (local)": 0.1,
        "Monthly Pass": 5,
        "Taxi 1km": 0.18,
        "Gasoline (1L)": 0.9,
        "Volkswagen Golf": 32000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 38,
        "Mobile Plan": 4,
        "Internet (60 Mbps)": 14,
        "Fitness Club/month": 12,
      },
      housing: {
        "1BR Center": 160,
        "1BR Outside": 90,
        "3BR Center": 380,
        "3BR Outside": 210,
        "Price/m² Center": 650,
        "Price/m² Outside": 350,
      },
      salaries: {
        "Average Net Salary": 220,
        "Mortgage Interest Rate": 13.0,
      },
    },
  },
  {
    slug: "bandar-seri-begawan",
    name: "Bandar Seri Begawan",
    country: "Brunei",
    countryCode: "BN",
    continent: "Asia",
    costIndex: 48,
    rentIndex: 40,
    qualityOfLife: 68,
    purchasingPower: 72,
    safety: 80,
    healthcare: 72,
    climate: 52,
    trafficCommute: 55,
    population: "0.1M",
    currency: "BND",
    avgMonthlyCost: 1500,
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 4,
        "Meal for 2 (mid-range)": 18,
        "McMeal at McDonald's": 5,
        "Domestic Beer (0.5L)": 0,
        "Imported Beer (0.33L)": 0,
        "Cappuccino": 3,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 1.5,
        "Bread (500g)": 1,
        "Rice (1kg)": 1,
        "Eggs (12)": 2.2,
        "Chicken (1kg)": 4,
        "Beef (1kg)": 9,
        "Apples (1kg)": 3,
        "Banana (1kg)": 1,
        "Tomato (1kg)": 2,
        "Potato (1kg)": 1.2,
        "Onion (1kg)": 1,
        "Water (1.5L)": 0.6,
      },
      transport: {
        "1-way Ticket (local)": 0.5,
        "Monthly Pass": 20,
        "Taxi 1km": 1,
        "Gasoline (1L)": 0.4,
        "Volkswagen Golf": 40000,
        "Toyota Corolla": 30000,
      },
      utilities: {
        "Basic (85m² apt)": 60,
        "Mobile Plan": 18,
        "Internet (60 Mbps)": 35,
        "Fitness Club/month": 45,
      },
      housing: {
        "1BR Center": 650,
        "1BR Outside": 400,
        "3BR Center": 1500,
        "3BR Outside": 900,
        "Price/m² Center": 2500,
        "Price/m² Outside": 1500,
      },
      salaries: {
        "Average Net Salary": 1800,
        "Mortgage Interest Rate": 5.5,
      },
    },
  },
  {
    slug: "dili-east-timor",
    name: "Dili",
    country: "Timor-Leste",
    countryCode: "TL",
    continent: "Asia",
    costIndex: 32,
    rentIndex: 26,
    qualityOfLife: 40,
    purchasingPower: 28,
    safety: 48,
    healthcare: 35,
    climate: 58,
    trafficCommute: 28,
    population: "0.3M",
    currency: "USD",
    avgMonthlyCost: 850,
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 3,
        "Meal for 2 (mid-range)": 12,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 2,
        "Imported Beer (0.33L)": 3,
        "Cappuccino": 2.5,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 2,
        "Bread (500g)": 1,
        "Rice (1kg)": 0.7,
        "Eggs (12)": 2,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 6,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.5,
        "Tomato (1kg)": 1.2,
        "Potato (1kg)": 1,
        "Onion (1kg)": 0.9,
        "Water (1.5L)": 0.5,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 10,
        "Taxi 1km": 0.4,
        "Gasoline (1L)": 1,
        "Volkswagen Golf": 35000,
        "Toyota Corolla": 25000,
      },
      utilities: {
        "Basic (85m² apt)": 60,
        "Mobile Plan": 8,
        "Internet (60 Mbps)": 30,
        "Fitness Club/month": 20,
      },
      housing: {
        "1BR Center": 400,
        "1BR Outside": 230,
        "3BR Center": 950,
        "3BR Outside": 540,
        "Price/m² Center": 1500,
        "Price/m² Outside": 800,
      },
      salaries: {
        "Average Net Salary": 350,
        "Mortgage Interest Rate": 10.0,
      },
    },
  },
  {
    slug: "taipei-tw",
    name: "Taipei",
    country: "Taiwan",
    countryCode: "TW",
    continent: "Asia",
    costIndex: 62,
    rentIndex: 55,
    qualityOfLife: 84,
    purchasingPower: 76,
    safety: 84,
    healthcare: 88,
    climate: 62,
    trafficCommute: 65,
    population: "2.7M",
    currency: "TWD",
    avgMonthlyCost: 2000,
    image: "https://images.unsplash.com/photo-1470219556762-1771e7f9427d?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 4,
        "Meal for 2 (mid-range)": 22,
        "McMeal at McDonald's": 5,
        "Domestic Beer (0.5L)": 2,
        "Imported Beer (0.33L)": 4,
        "Cappuccino": 3.5,
        "Coke/Pepsi (0.33L)": 1.2,
        "Water (0.33L)": 0.8,
      },
      markets: {
        "Milk (1L)": 2,
        "Bread (500g)": 1.5,
        "Rice (1kg)": 1.5,
        "Eggs (12)": 2.2,
        "Chicken (1kg)": 6,
        "Beef (1kg)": 15,
        "Apples (1kg)": 4,
        "Banana (1kg)": 1.5,
        "Tomato (1kg)": 2.5,
        "Potato (1kg)": 2,
        "Onion (1kg)": 1.5,
        "Water (1.5L)": 0.7,
      },
      transport: {
        "1-way Ticket (local)": 0.7,
        "Monthly Pass": 45,
        "Taxi 1km": 1.5,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 30000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 90,
        "Mobile Plan": 22,
        "Internet (60 Mbps)": 22,
        "Fitness Club/month": 50,
      },
      housing: {
        "1BR Center": 900,
        "1BR Outside": 600,
        "3BR Center": 2200,
        "3BR Outside": 1300,
        "Price/m² Center": 8000,
        "Price/m² Outside": 4500,
      },
      salaries: {
        "Average Net Salary": 2000,
        "Mortgage Interest Rate": 2.5,
      },
    },
  },
  {
    slug: "antananarivo",
    name: "Antananarivo",
    country: "Madagascar",
    countryCode: "MG",
    continent: "Africa",
    costIndex: 22,
    rentIndex: 16,
    qualityOfLife: 36,
    purchasingPower: 24,
    safety: 38,
    healthcare: 28,
    climate: 68,
    trafficCommute: 20,
    population: "3.6M",
    currency: "MGA",
    avgMonthlyCost: 550,
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.3,
      },
      markets: {
        "Milk (1L)": 0.8,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.4,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 2.5,
        "Beef (1kg)": 4,
        "Apples (1kg)": 2,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.4,
        "Onion (1kg)": 0.35,
        "Water (1.5L)": 0.3,
      },
      transport: {
        "1-way Ticket (local)": 0.15,
        "Monthly Pass": 6,
        "Taxi 1km": 0.25,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 35,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 22,
        "Fitness Club/month": 15,
      },
      housing: {
        "1BR Center": 200,
        "1BR Outside": 110,
        "3BR Center": 460,
        "3BR Outside": 260,
        "Price/m² Center": 750,
        "Price/m² Outside": 400,
      },
      salaries: {
        "Average Net Salary": 200,
        "Mortgage Interest Rate": 20.0,
      },
    },
  },
  {
    slug: "lilongwe",
    name: "Lilongwe",
    country: "Malawi",
    countryCode: "MW",
    continent: "Africa",
    costIndex: 22,
    rentIndex: 18,
    qualityOfLife: 38,
    purchasingPower: 26,
    safety: 44,
    healthcare: 30,
    climate: 68,
    trafficCommute: 22,
    population: "1.1M",
    currency: "MWK",
    avgMonthlyCost: 550,
    image: "https://images.unsplash.com/photo-1611348586754-ea3e0a748fca?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.2,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.3,
      },
      markets: {
        "Milk (1L)": 0.8,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 2.5,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.4,
        "Onion (1kg)": 0.35,
        "Water (1.5L)": 0.3,
      },
      transport: {
        "1-way Ticket (local)": 0.15,
        "Monthly Pass": 7,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.4,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 38,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 25,
        "Fitness Club/month": 16,
      },
      housing: {
        "1BR Center": 220,
        "1BR Outside": 120,
        "3BR Center": 520,
        "3BR Outside": 290,
        "Price/m² Center": 800,
        "Price/m² Outside": 430,
      },
      salaries: {
        "Average Net Salary": 180,
        "Mortgage Interest Rate": 22.0,
      },
    },
  },
  {
    slug: "lusaka",
    name: "Lusaka",
    country: "Zambia",
    countryCode: "ZM",
    continent: "Africa",
    costIndex: 28,
    rentIndex: 24,
    qualityOfLife: 44,
    purchasingPower: 32,
    safety: 42,
    healthcare: 38,
    climate: 70,
    trafficCommute: 22,
    population: "2.7M",
    currency: "ZMW",
    avgMonthlyCost: 700,
    image: "https://images.unsplash.com/photo-1577948000111-9c970dfe3743?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 3,
        "Meal for 2 (mid-range)": 12,
        "McMeal at McDonald's": 4,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 2,
        "Coke/Pepsi (0.33L)": 0.7,
        "Water (0.33L)": 0.4,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.6,
        "Rice (1kg)": 0.7,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5.5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.4,
        "Tomato (1kg)": 0.7,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.45,
        "Water (1.5L)": 0.4,
      },
      transport: {
        "1-way Ticket (local)": 0.25,
        "Monthly Pass": 12,
        "Taxi 1km": 0.4,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 28000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 55,
        "Mobile Plan": 8,
        "Internet (60 Mbps)": 35,
        "Fitness Club/month": 22,
      },
      housing: {
        "1BR Center": 350,
        "1BR Outside": 200,
        "3BR Center": 820,
        "3BR Outside": 460,
        "Price/m² Center": 1300,
        "Price/m² Outside": 720,
      },
      salaries: {
        "Average Net Salary": 350,
        "Mortgage Interest Rate": 25.0,
      },
    },
  },
  {
    slug: "gaborone",
    name: "Gaborone",
    country: "Botswana",
    countryCode: "BW",
    continent: "Africa",
    costIndex: 38,
    rentIndex: 32,
    qualityOfLife: 55,
    purchasingPower: 44,
    safety: 50,
    healthcare: 52,
    climate: 68,
    trafficCommute: 35,
    population: "0.3M",
    currency: "BWP",
    avgMonthlyCost: 1000,
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 4,
        "Meal for 2 (mid-range)": 16,
        "McMeal at McDonald's": 5,
        "Domestic Beer (0.5L)": 2,
        "Imported Beer (0.33L)": 3,
        "Cappuccino": 2.5,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 1.1,
        "Bread (500g)": 0.8,
        "Rice (1kg)": 1,
        "Eggs (12)": 2,
        "Chicken (1kg)": 4,
        "Beef (1kg)": 6,
        "Apples (1kg)": 2,
        "Banana (1kg)": 0.8,
        "Tomato (1kg)": 1,
        "Potato (1kg)": 0.8,
        "Onion (1kg)": 0.7,
        "Water (1.5L)": 0.5,
      },
      transport: {
        "1-way Ticket (local)": 0.4,
        "Monthly Pass": 18,
        "Taxi 1km": 0.5,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 28000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 75,
        "Mobile Plan": 10,
        "Internet (60 Mbps)": 38,
        "Fitness Club/month": 28,
      },
      housing: {
        "1BR Center": 480,
        "1BR Outside": 280,
        "3BR Center": 1100,
        "3BR Outside": 640,
        "Price/m² Center": 1800,
        "Price/m² Outside": 1000,
      },
      salaries: {
        "Average Net Salary": 700,
        "Mortgage Interest Rate": 8.5,
      },
    },
  },
  {
    slug: "windhoek",
    name: "Windhoek",
    country: "Namibia",
    countryCode: "NA",
    continent: "Africa",
    costIndex: 42,
    rentIndex: 36,
    qualityOfLife: 56,
    purchasingPower: 46,
    safety: 42,
    healthcare: 55,
    climate: 72,
    trafficCommute: 38,
    population: "0.4M",
    currency: "NAD",
    avgMonthlyCost: 1100,
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 5,
        "Meal for 2 (mid-range)": 20,
        "McMeal at McDonald's": 5,
        "Domestic Beer (0.5L)": 2,
        "Imported Beer (0.33L)": 3,
        "Cappuccino": 2.5,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.6,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.8,
        "Rice (1kg)": 1.2,
        "Eggs (12)": 2.2,
        "Chicken (1kg)": 4.5,
        "Beef (1kg)": 7,
        "Apples (1kg)": 1.8,
        "Banana (1kg)": 0.9,
        "Tomato (1kg)": 1.2,
        "Potato (1kg)": 0.9,
        "Onion (1kg)": 0.7,
        "Water (1.5L)": 0.6,
      },
      transport: {
        "1-way Ticket (local)": 0.5,
        "Monthly Pass": 22,
        "Taxi 1km": 0.6,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 28000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 80,
        "Mobile Plan": 12,
        "Internet (60 Mbps)": 42,
        "Fitness Club/month": 30,
      },
      housing: {
        "1BR Center": 520,
        "1BR Outside": 320,
        "3BR Center": 1200,
        "3BR Outside": 700,
        "Price/m² Center": 2000,
        "Price/m² Outside": 1100,
      },
      salaries: {
        "Average Net Salary": 750,
        "Mortgage Interest Rate": 10.5,
      },
    },
  },
  {
    slug: "libreville",
    name: "Libreville",
    country: "Gabon",
    countryCode: "GA",
    continent: "Africa",
    costIndex: 40,
    rentIndex: 34,
    qualityOfLife: 46,
    purchasingPower: 38,
    safety: 44,
    healthcare: 45,
    climate: 62,
    trafficCommute: 25,
    population: "0.8M",
    currency: "XAF",
    avgMonthlyCost: 1100,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 5,
        "Meal for 2 (mid-range)": 20,
        "McMeal at McDonald's": 5,
        "Domestic Beer (0.5L)": 2.5,
        "Imported Beer (0.33L)": 4,
        "Cappuccino": 2.5,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 1.5,
        "Bread (500g)": 0.7,
        "Rice (1kg)": 1,
        "Eggs (12)": 2,
        "Chicken (1kg)": 4,
        "Beef (1kg)": 7,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.5,
        "Tomato (1kg)": 1,
        "Potato (1kg)": 0.8,
        "Onion (1kg)": 0.7,
        "Water (1.5L)": 0.5,
      },
      transport: {
        "1-way Ticket (local)": 0.35,
        "Monthly Pass": 15,
        "Taxi 1km": 0.5,
        "Gasoline (1L)": 0.8,
        "Volkswagen Golf": 30000,
        "Toyota Corolla": 24000,
      },
      utilities: {
        "Basic (85m² apt)": 80,
        "Mobile Plan": 12,
        "Internet (60 Mbps)": 45,
        "Fitness Club/month": 35,
      },
      housing: {
        "1BR Center": 550,
        "1BR Outside": 330,
        "3BR Center": 1250,
        "3BR Outside": 730,
        "Price/m² Center": 2000,
        "Price/m² Outside": 1100,
      },
      salaries: {
        "Average Net Salary": 700,
        "Mortgage Interest Rate": 8.0,
      },
    },
  },
  {
    slug: "yaounde",
    name: "Yaoundé",
    country: "Cameroon",
    countryCode: "CM",
    continent: "Africa",
    costIndex: 30,
    rentIndex: 24,
    qualityOfLife: 42,
    purchasingPower: 32,
    safety: 40,
    healthcare: 38,
    climate: 65,
    trafficCommute: 22,
    population: "3.6M",
    currency: "XAF",
    avgMonthlyCost: 800,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 3,
        "Meal for 2 (mid-range)": 12,
        "McMeal at McDonald's": 4,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 2,
        "Coke/Pepsi (0.33L)": 0.7,
        "Water (0.33L)": 0.4,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.7,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5.5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.4,
        "Tomato (1kg)": 0.7,
        "Potato (1kg)": 0.55,
        "Onion (1kg)": 0.5,
        "Water (1.5L)": 0.4,
      },
      transport: {
        "1-way Ticket (local)": 0.25,
        "Monthly Pass": 12,
        "Taxi 1km": 0.35,
        "Gasoline (1L)": 1.1,
        "Volkswagen Golf": 28000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 60,
        "Mobile Plan": 8,
        "Internet (60 Mbps)": 30,
        "Fitness Club/month": 25,
      },
      housing: {
        "1BR Center": 320,
        "1BR Outside": 185,
        "3BR Center": 740,
        "3BR Outside": 420,
        "Price/m² Center": 1200,
        "Price/m² Outside": 650,
      },
      salaries: {
        "Average Net Salary": 380,
        "Mortgage Interest Rate": 8.5,
      },
    },
  },
  {
    slug: "conakry",
    name: "Conakry",
    country: "Guinea",
    countryCode: "GN",
    continent: "Africa",
    costIndex: 26,
    rentIndex: 20,
    qualityOfLife: 34,
    purchasingPower: 24,
    safety: 35,
    healthcare: 28,
    climate: 62,
    trafficCommute: 18,
    population: "1.9M",
    currency: "GNF",
    avgMonthlyCost: 650,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.6,
        "Water (0.33L)": 0.35,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.6,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.35,
        "Tomato (1kg)": 0.6,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.4,
        "Water (1.5L)": 0.35,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 8,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.4,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 45,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 25,
        "Fitness Club/month": 18,
      },
      housing: {
        "1BR Center": 280,
        "1BR Outside": 160,
        "3BR Center": 650,
        "3BR Outside": 370,
        "Price/m² Center": 1000,
        "Price/m² Outside": 550,
      },
      salaries: {
        "Average Net Salary": 200,
        "Mortgage Interest Rate": 18.0,
      },
    },
  },
  {
    slug: "freetown",
    name: "Freetown",
    country: "Sierra Leone",
    countryCode: "SL",
    continent: "Africa",
    costIndex: 24,
    rentIndex: 18,
    qualityOfLife: 32,
    purchasingPower: 22,
    safety: 52,
    healthcare: 26,
    climate: 62,
    trafficCommute: 18,
    population: "1.1M",
    currency: "SLL",
    avgMonthlyCost: 600,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.6,
        "Water (0.33L)": 0.35,
      },
      markets: {
        "Milk (1L)": 1.2,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.4,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 5,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.6,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.4,
        "Water (1.5L)": 0.35,
      },
      transport: {
        "1-way Ticket (local)": 0.15,
        "Monthly Pass": 7,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.5,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 40,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 30,
        "Fitness Club/month": 15,
      },
      housing: {
        "1BR Center": 260,
        "1BR Outside": 145,
        "3BR Center": 600,
        "3BR Outside": 340,
        "Price/m² Center": 900,
        "Price/m² Outside": 480,
      },
      salaries: {
        "Average Net Salary": 170,
        "Mortgage Interest Rate": 20.0,
      },
    },
  },
  {
    slug: "ouagadougou",
    name: "Ouagadougou",
    country: "Burkina Faso",
    countryCode: "BF",
    continent: "Africa",
    costIndex: 24,
    rentIndex: 18,
    qualityOfLife: 34,
    purchasingPower: 22,
    safety: 28,
    healthcare: 26,
    climate: 52,
    trafficCommute: 20,
    population: "3.5M",
    currency: "XOF",
    avgMonthlyCost: 600,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.2,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.3,
      },
      markets: {
        "Milk (1L)": 0.9,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.3,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.4,
        "Onion (1kg)": 0.35,
        "Water (1.5L)": 0.3,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 8,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 24000,
        "Toyota Corolla": 19000,
      },
      utilities: {
        "Basic (85m² apt)": 40,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 28,
        "Fitness Club/month": 16,
      },
      housing: {
        "1BR Center": 240,
        "1BR Outside": 135,
        "3BR Center": 560,
        "3BR Outside": 315,
        "Price/m² Center": 900,
        "Price/m² Outside": 480,
      },
      salaries: {
        "Average Net Salary": 180,
        "Mortgage Interest Rate": 8.5,
      },
    },
  },
  {
    slug: "bamako",
    name: "Bamako",
    country: "Mali",
    countryCode: "ML",
    continent: "Africa",
    costIndex: 24,
    rentIndex: 18,
    qualityOfLife: 32,
    purchasingPower: 20,
    safety: 30,
    healthcare: 24,
    climate: 50,
    trafficCommute: 18,
    population: "2.7M",
    currency: "XOF",
    avgMonthlyCost: 600,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.2,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.2,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.28,
      },
      markets: {
        "Milk (1L)": 0.9,
        "Bread (500g)": 0.35,
        "Rice (1kg)": 0.45,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 2.8,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.28,
        "Tomato (1kg)": 0.45,
        "Potato (1kg)": 0.38,
        "Onion (1kg)": 0.32,
        "Water (1.5L)": 0.28,
      },
      transport: {
        "1-way Ticket (local)": 0.18,
        "Monthly Pass": 8,
        "Taxi 1km": 0.28,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 24000,
        "Toyota Corolla": 19000,
      },
      utilities: {
        "Basic (85m² apt)": 38,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 26,
        "Fitness Club/month": 14,
      },
      housing: {
        "1BR Center": 220,
        "1BR Outside": 125,
        "3BR Center": 520,
        "3BR Outside": 295,
        "Price/m² Center": 850,
        "Price/m² Outside": 450,
      },
      salaries: {
        "Average Net Salary": 175,
        "Mortgage Interest Rate": 8.0,
      },
    },
  },
  {
    slug: "niamey",
    name: "Niamey",
    country: "Niger",
    countryCode: "NE",
    continent: "Africa",
    costIndex: 22,
    rentIndex: 16,
    qualityOfLife: 28,
    purchasingPower: 18,
    safety: 32,
    healthcare: 22,
    climate: 45,
    trafficCommute: 16,
    population: "1.3M",
    currency: "XOF",
    avgMonthlyCost: 530,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 1.8,
        "Meal for 2 (mid-range)": 7,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1,
        "Imported Beer (0.33L)": 1.8,
        "Cappuccino": 1.2,
        "Coke/Pepsi (0.33L)": 0.45,
        "Water (0.33L)": 0.25,
      },
      markets: {
        "Milk (1L)": 0.8,
        "Bread (500g)": 0.3,
        "Rice (1kg)": 0.4,
        "Eggs (12)": 1.1,
        "Chicken (1kg)": 2.5,
        "Beef (1kg)": 4,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.25,
        "Tomato (1kg)": 0.4,
        "Potato (1kg)": 0.32,
        "Onion (1kg)": 0.28,
        "Water (1.5L)": 0.25,
      },
      transport: {
        "1-way Ticket (local)": 0.15,
        "Monthly Pass": 6,
        "Taxi 1km": 0.25,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 22000,
        "Toyota Corolla": 18000,
      },
      utilities: {
        "Basic (85m² apt)": 35,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 22,
        "Fitness Club/month": 12,
      },
      housing: {
        "1BR Center": 190,
        "1BR Outside": 105,
        "3BR Center": 445,
        "3BR Outside": 250,
        "Price/m² Center": 720,
        "Price/m² Outside": 380,
      },
      salaries: {
        "Average Net Salary": 140,
        "Mortgage Interest Rate": 9.0,
      },
    },
  },
  {
    slug: "ndjamena",
    name: "N'Djamena",
    country: "Chad",
    countryCode: "TD",
    continent: "Africa",
    costIndex: 26,
    rentIndex: 20,
    qualityOfLife: 28,
    purchasingPower: 18,
    safety: 28,
    healthcare: 22,
    climate: 44,
    trafficCommute: 18,
    population: "1.4M",
    currency: "XAF",
    avgMonthlyCost: 650,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.3,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.3,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2.8,
        "Banana (1kg)": 0.4,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.4,
        "Onion (1kg)": 0.35,
        "Water (1.5L)": 0.3,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 8,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.4,
        "Volkswagen Golf": 24000,
        "Toyota Corolla": 19000,
      },
      utilities: {
        "Basic (85m² apt)": 48,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 28,
        "Fitness Club/month": 18,
      },
      housing: {
        "1BR Center": 250,
        "1BR Outside": 140,
        "3BR Center": 580,
        "3BR Outside": 330,
        "Price/m² Center": 950,
        "Price/m² Outside": 500,
      },
      salaries: {
        "Average Net Salary": 180,
        "Mortgage Interest Rate": 14.0,
      },
    },
  },
  {
    slug: "bangui",
    name: "Bangui",
    country: "Central African Republic",
    countryCode: "CF",
    continent: "Africa",
    costIndex: 22,
    rentIndex: 16,
    qualityOfLife: 22,
    purchasingPower: 15,
    safety: 18,
    healthcare: 18,
    climate: 60,
    trafficCommute: 15,
    population: "0.9M",
    currency: "XAF",
    avgMonthlyCost: 530,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.2,
        "Coke/Pepsi (0.33L)": 0.45,
        "Water (0.33L)": 0.28,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.35,
        "Rice (1kg)": 0.45,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 2.8,
        "Beef (1kg)": 4,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.28,
        "Tomato (1kg)": 0.45,
        "Potato (1kg)": 0.35,
        "Onion (1kg)": 0.3,
        "Water (1.5L)": 0.28,
      },
      transport: {
        "1-way Ticket (local)": 0.15,
        "Monthly Pass": 6,
        "Taxi 1km": 0.25,
        "Gasoline (1L)": 1.6,
        "Volkswagen Golf": 22000,
        "Toyota Corolla": 18000,
      },
      utilities: {
        "Basic (85m² apt)": 35,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 28,
        "Fitness Club/month": 12,
      },
      housing: {
        "1BR Center": 180,
        "1BR Outside": 100,
        "3BR Center": 420,
        "3BR Outside": 235,
        "Price/m² Center": 680,
        "Price/m² Outside": 360,
      },
      salaries: {
        "Average Net Salary": 120,
        "Mortgage Interest Rate": 15.0,
      },
    },
  },
  {
    slug: "brazzaville",
    name: "Brazzaville",
    country: "Republic of Congo",
    countryCode: "CG",
    continent: "Africa",
    costIndex: 30,
    rentIndex: 24,
    qualityOfLife: 38,
    purchasingPower: 28,
    safety: 38,
    healthcare: 32,
    climate: 62,
    trafficCommute: 20,
    population: "1.8M",
    currency: "XAF",
    avgMonthlyCost: 780,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 3,
        "Meal for 2 (mid-range)": 12,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 2,
        "Coke/Pepsi (0.33L)": 0.6,
        "Water (0.33L)": 0.35,
      },
      markets: {
        "Milk (1L)": 1.2,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.6,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.35,
        "Tomato (1kg)": 0.6,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.42,
        "Water (1.5L)": 0.35,
      },
      transport: {
        "1-way Ticket (local)": 0.22,
        "Monthly Pass": 10,
        "Taxi 1km": 0.35,
        "Gasoline (1L)": 0.85,
        "Volkswagen Golf": 28000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 55,
        "Mobile Plan": 7,
        "Internet (60 Mbps)": 32,
        "Fitness Club/month": 20,
      },
      housing: {
        "1BR Center": 320,
        "1BR Outside": 180,
        "3BR Center": 740,
        "3BR Outside": 420,
        "Price/m² Center": 1200,
        "Price/m² Outside": 640,
      },
      salaries: {
        "Average Net Salary": 350,
        "Mortgage Interest Rate": 12.0,
      },
    },
  },
  {
    slug: "kinshasa",
    name: "Kinshasa",
    country: "DR Congo",
    countryCode: "CD",
    continent: "Africa",
    costIndex: 28,
    rentIndex: 22,
    qualityOfLife: 28,
    purchasingPower: 18,
    safety: 22,
    healthcare: 22,
    climate: 65,
    trafficCommute: 15,
    population: "15.0M",
    currency: "CDF",
    avgMonthlyCost: 680,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.2,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 1.8,
        "Coke/Pepsi (0.33L)": 0.6,
        "Water (0.33L)": 0.35,
      },
      markets: {
        "Milk (1L)": 1.2,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.6,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.4,
        "Water (1.5L)": 0.35,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 9,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 50,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 32,
        "Fitness Club/month": 18,
      },
      housing: {
        "1BR Center": 290,
        "1BR Outside": 165,
        "3BR Center": 680,
        "3BR Outside": 385,
        "Price/m² Center": 1100,
        "Price/m² Outside": 580,
      },
      salaries: {
        "Average Net Salary": 160,
        "Mortgage Interest Rate": 18.0,
      },
    },
  },
  {
    slug: "mogadishu",
    name: "Mogadishu",
    country: "Somalia",
    countryCode: "SO",
    continent: "Africa",
    costIndex: 25,
    rentIndex: 18,
    qualityOfLife: 20,
    purchasingPower: 14,
    safety: 10,
    healthcare: 18,
    climate: 52,
    trafficCommute: 14,
    population: "2.4M",
    currency: "SOS",
    avgMonthlyCost: 580,
    image: "https://images.unsplash.com/photo-1611348586754-ea3e0a748fca?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 0,
        "Imported Beer (0.33L)": 0,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.28,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.3,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.4,
        "Onion (1kg)": 0.35,
        "Water (1.5L)": 0.28,
      },
      transport: {
        "1-way Ticket (local)": 0.15,
        "Monthly Pass": 6,
        "Taxi 1km": 0.25,
        "Gasoline (1L)": 1.1,
        "Volkswagen Golf": 22000,
        "Toyota Corolla": 18000,
      },
      utilities: {
        "Basic (85m² apt)": 40,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 30,
        "Fitness Club/month": 14,
      },
      housing: {
        "1BR Center": 230,
        "1BR Outside": 130,
        "3BR Center": 540,
        "3BR Outside": 305,
        "Price/m² Center": 880,
        "Price/m² Outside": 460,
      },
      salaries: {
        "Average Net Salary": 130,
        "Mortgage Interest Rate": 18.0,
      },
    },
  },
  {
    slug: "juba",
    name: "Juba",
    country: "South Sudan",
    countryCode: "SS",
    continent: "Africa",
    costIndex: 30,
    rentIndex: 22,
    qualityOfLife: 18,
    purchasingPower: 12,
    safety: 14,
    healthcare: 16,
    climate: 48,
    trafficCommute: 14,
    population: "0.5M",
    currency: "SSP",
    avgMonthlyCost: 700,
    image: "https://images.unsplash.com/photo-1611348586754-ea3e0a748fca?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 3,
        "Meal for 2 (mid-range)": 12,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 2,
        "Imported Beer (0.33L)": 3,
        "Cappuccino": 2,
        "Coke/Pepsi (0.33L)": 0.7,
        "Water (0.33L)": 0.4,
      },
      markets: {
        "Milk (1L)": 1.2,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.6,
        "Eggs (12)": 1.6,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.4,
        "Tomato (1kg)": 0.7,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.45,
        "Water (1.5L)": 0.4,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 8,
        "Taxi 1km": 0.35,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 55,
        "Mobile Plan": 8,
        "Internet (60 Mbps)": 35,
        "Fitness Club/month": 18,
      },
      housing: {
        "1BR Center": 300,
        "1BR Outside": 170,
        "3BR Center": 700,
        "3BR Outside": 395,
        "Price/m² Center": 1100,
        "Price/m² Outside": 580,
      },
      salaries: {
        "Average Net Salary": 150,
        "Mortgage Interest Rate": 20.0,
      },
    },
  },
  {
    slug: "khartoum",
    name: "Khartoum",
    country: "Sudan",
    countryCode: "SD",
    continent: "Africa",
    costIndex: 24,
    rentIndex: 18,
    qualityOfLife: 28,
    purchasingPower: 18,
    safety: 24,
    healthcare: 28,
    climate: 40,
    trafficCommute: 20,
    population: "7.3M",
    currency: "SDG",
    avgMonthlyCost: 580,
    image: "https://images.unsplash.com/photo-1611348586754-ea3e0a748fca?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 0,
        "Imported Beer (0.33L)": 0,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.4,
        "Water (0.33L)": 0.25,
      },
      markets: {
        "Milk (1L)": 0.8,
        "Bread (500g)": 0.3,
        "Rice (1kg)": 0.4,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 5,
        "Apples (1kg)": 1.8,
        "Banana (1kg)": 0.5,
        "Tomato (1kg)": 0.4,
        "Potato (1kg)": 0.32,
        "Onion (1kg)": 0.28,
        "Water (1.5L)": 0.25,
      },
      transport: {
        "1-way Ticket (local)": 0.12,
        "Monthly Pass": 5,
        "Taxi 1km": 0.2,
        "Gasoline (1L)": 0.6,
        "Volkswagen Golf": 22000,
        "Toyota Corolla": 18000,
      },
      utilities: {
        "Basic (85m² apt)": 35,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 20,
        "Fitness Club/month": 14,
      },
      housing: {
        "1BR Center": 220,
        "1BR Outside": 120,
        "3BR Center": 520,
        "3BR Outside": 295,
        "Price/m² Center": 850,
        "Price/m² Outside": 450,
      },
      salaries: {
        "Average Net Salary": 130,
        "Mortgage Interest Rate": 20.0,
      },
    },
  },
  {
    slug: "asmara",
    name: "Asmara",
    country: "Eritrea",
    countryCode: "ER",
    continent: "Africa",
    costIndex: 20,
    rentIndex: 14,
    qualityOfLife: 30,
    purchasingPower: 16,
    safety: 45,
    healthcare: 28,
    climate: 70,
    trafficCommute: 22,
    population: "0.8M",
    currency: "ERN",
    avgMonthlyCost: 480,
    image: "https://images.unsplash.com/photo-1611348586754-ea3e0a748fca?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 1.5,
        "Meal for 2 (mid-range)": 6,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 0.8,
        "Imported Beer (0.33L)": 1.5,
        "Cappuccino": 1,
        "Coke/Pepsi (0.33L)": 0.35,
        "Water (0.33L)": 0.22,
      },
      markets: {
        "Milk (1L)": 0.7,
        "Bread (500g)": 0.3,
        "Rice (1kg)": 0.4,
        "Eggs (12)": 1,
        "Chicken (1kg)": 2.5,
        "Beef (1kg)": 4,
        "Apples (1kg)": 1.8,
        "Banana (1kg)": 0.4,
        "Tomato (1kg)": 0.4,
        "Potato (1kg)": 0.3,
        "Onion (1kg)": 0.25,
        "Water (1.5L)": 0.22,
      },
      transport: {
        "1-way Ticket (local)": 0.1,
        "Monthly Pass": 4,
        "Taxi 1km": 0.18,
        "Gasoline (1L)": 0.9,
        "Volkswagen Golf": 20000,
        "Toyota Corolla": 16000,
      },
      utilities: {
        "Basic (85m² apt)": 28,
        "Mobile Plan": 4,
        "Internet (60 Mbps)": 15,
        "Fitness Club/month": 10,
      },
      housing: {
        "1BR Center": 160,
        "1BR Outside": 90,
        "3BR Center": 375,
        "3BR Outside": 210,
        "Price/m² Center": 600,
        "Price/m² Outside": 320,
      },
      salaries: {
        "Average Net Salary": 100,
        "Mortgage Interest Rate": 12.0,
      },
    },
  },
  {
    slug: "djibouti-city",
    name: "Djibouti City",
    country: "Djibouti",
    countryCode: "DJ",
    continent: "Africa",
    costIndex: 38,
    rentIndex: 30,
    qualityOfLife: 42,
    purchasingPower: 30,
    safety: 52,
    healthcare: 40,
    climate: 42,
    trafficCommute: 28,
    population: "0.6M",
    currency: "DJF",
    avgMonthlyCost: 950,
    image: "https://images.unsplash.com/photo-1611348586754-ea3e0a748fca?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 4,
        "Meal for 2 (mid-range)": 16,
        "McMeal at McDonald's": 5,
        "Domestic Beer (0.5L)": 3,
        "Imported Beer (0.33L)": 4,
        "Cappuccino": 2.5,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 1.5,
        "Bread (500g)": 0.6,
        "Rice (1kg)": 0.8,
        "Eggs (12)": 2,
        "Chicken (1kg)": 5,
        "Beef (1kg)": 8,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.8,
        "Tomato (1kg)": 1.2,
        "Potato (1kg)": 1,
        "Onion (1kg)": 0.8,
        "Water (1.5L)": 0.5,
      },
      transport: {
        "1-way Ticket (local)": 0.4,
        "Monthly Pass": 16,
        "Taxi 1km": 0.5,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 28000,
        "Toyota Corolla": 22000,
      },
      utilities: {
        "Basic (85m² apt)": 65,
        "Mobile Plan": 12,
        "Internet (60 Mbps)": 35,
        "Fitness Club/month": 28,
      },
      housing: {
        "1BR Center": 480,
        "1BR Outside": 280,
        "3BR Center": 1100,
        "3BR Outside": 630,
        "Price/m² Center": 1800,
        "Price/m² Outside": 950,
      },
      salaries: {
        "Average Net Salary": 400,
        "Mortgage Interest Rate": 11.0,
      },
    },
  },
  {
    slug: "lome",
    name: "Lomé",
    country: "Togo",
    countryCode: "TG",
    continent: "Africa",
    costIndex: 26,
    rentIndex: 20,
    qualityOfLife: 38,
    purchasingPower: 26,
    safety: 48,
    healthcare: 34,
    climate: 65,
    trafficCommute: 20,
    population: "1.4M",
    currency: "XOF",
    avgMonthlyCost: 650,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.2,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.3,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.4,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.4,
        "Onion (1kg)": 0.35,
        "Water (1.5L)": 0.3,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 8,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 24000,
        "Toyota Corolla": 19000,
      },
      utilities: {
        "Basic (85m² apt)": 42,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 24,
        "Fitness Club/month": 16,
      },
      housing: {
        "1BR Center": 250,
        "1BR Outside": 140,
        "3BR Center": 580,
        "3BR Outside": 325,
        "Price/m² Center": 950,
        "Price/m² Outside": 500,
      },
      salaries: {
        "Average Net Salary": 200,
        "Mortgage Interest Rate": 8.5,
      },
    },
  },
  {
    slug: "cotonou",
    name: "Cotonou",
    country: "Benin",
    countryCode: "BJ",
    continent: "Africa",
    costIndex: 28,
    rentIndex: 22,
    qualityOfLife: 40,
    purchasingPower: 28,
    safety: 50,
    healthcare: 36,
    climate: 64,
    trafficCommute: 20,
    population: "0.7M",
    currency: "XOF",
    avgMonthlyCost: 700,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.2,
        "Imported Beer (0.33L)": 2.2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.55,
        "Water (0.33L)": 0.32,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.4,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.4,
        "Chicken (1kg)": 3.2,
        "Beef (1kg)": 5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.32,
        "Tomato (1kg)": 0.5,
        "Potato (1kg)": 0.42,
        "Onion (1kg)": 0.38,
        "Water (1.5L)": 0.32,
      },
      transport: {
        "1-way Ticket (local)": 0.22,
        "Monthly Pass": 9,
        "Taxi 1km": 0.32,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 45,
        "Mobile Plan": 6,
        "Internet (60 Mbps)": 26,
        "Fitness Club/month": 18,
      },
      housing: {
        "1BR Center": 270,
        "1BR Outside": 150,
        "3BR Center": 630,
        "3BR Outside": 355,
        "Price/m² Center": 1000,
        "Price/m² Outside": 530,
      },
      salaries: {
        "Average Net Salary": 220,
        "Mortgage Interest Rate": 8.5,
      },
    },
  },
  {
    slug: "monrovia",
    name: "Monrovia",
    country: "Liberia",
    countryCode: "LR",
    continent: "Africa",
    costIndex: 26,
    rentIndex: 20,
    qualityOfLife: 30,
    purchasingPower: 18,
    safety: 40,
    healthcare: 24,
    climate: 62,
    trafficCommute: 16,
    population: "1.5M",
    currency: "LRD",
    avgMonthlyCost: 620,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.6,
        "Water (0.33L)": 0.35,
      },
      markets: {
        "Milk (1L)": 1.5,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.6,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5.5,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.6,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.42,
        "Water (1.5L)": 0.35,
      },
      transport: {
        "1-way Ticket (local)": 0.18,
        "Monthly Pass": 7,
        "Taxi 1km": 0.28,
        "Gasoline (1L)": 1.4,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 45,
        "Mobile Plan": 7,
        "Internet (60 Mbps)": 30,
        "Fitness Club/month": 16,
      },
      housing: {
        "1BR Center": 260,
        "1BR Outside": 145,
        "3BR Center": 605,
        "3BR Outside": 340,
        "Price/m² Center": 960,
        "Price/m² Outside": 505,
      },
      salaries: {
        "Average Net Salary": 160,
        "Mortgage Interest Rate": 17.0,
      },
    },
  },
  {
    slug: "banjul",
    name: "Banjul",
    country: "Gambia",
    countryCode: "GM",
    continent: "Africa",
    costIndex: 24,
    rentIndex: 18,
    qualityOfLife: 38,
    purchasingPower: 24,
    safety: 52,
    healthcare: 30,
    climate: 66,
    trafficCommute: 18,
    population: "0.4M",
    currency: "GMD",
    avgMonthlyCost: 580,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.2,
        "Imported Beer (0.33L)": 2,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.5,
        "Water (0.33L)": 0.3,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.35,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.2,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.28,
        "Tomato (1kg)": 0.45,
        "Potato (1kg)": 0.38,
        "Onion (1kg)": 0.3,
        "Water (1.5L)": 0.3,
      },
      transport: {
        "1-way Ticket (local)": 0.15,
        "Monthly Pass": 6,
        "Taxi 1km": 0.25,
        "Gasoline (1L)": 1.2,
        "Volkswagen Golf": 22000,
        "Toyota Corolla": 18000,
      },
      utilities: {
        "Basic (85m² apt)": 38,
        "Mobile Plan": 5,
        "Internet (60 Mbps)": 22,
        "Fitness Club/month": 14,
      },
      housing: {
        "1BR Center": 210,
        "1BR Outside": 118,
        "3BR Center": 490,
        "3BR Outside": 275,
        "Price/m² Center": 800,
        "Price/m² Outside": 420,
      },
      salaries: {
        "Average Net Salary": 160,
        "Mortgage Interest Rate": 18.0,
      },
    },
  },
  {
    slug: "bissau",
    name: "Bissau",
    country: "Guinea-Bissau",
    countryCode: "GW",
    continent: "Africa",
    costIndex: 22,
    rentIndex: 16,
    qualityOfLife: 30,
    purchasingPower: 18,
    safety: 42,
    healthcare: 22,
    climate: 64,
    trafficCommute: 16,
    population: "0.5M",
    currency: "XOF",
    avgMonthlyCost: 520,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 1.8,
        "Meal for 2 (mid-range)": 7,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1,
        "Imported Beer (0.33L)": 1.8,
        "Cappuccino": 1.2,
        "Coke/Pepsi (0.33L)": 0.42,
        "Water (0.33L)": 0.25,
      },
      markets: {
        "Milk (1L)": 0.9,
        "Bread (500g)": 0.3,
        "Rice (1kg)": 0.4,
        "Eggs (12)": 1.1,
        "Chicken (1kg)": 2.8,
        "Beef (1kg)": 4,
        "Apples (1kg)": 2.5,
        "Banana (1kg)": 0.25,
        "Tomato (1kg)": 0.4,
        "Potato (1kg)": 0.32,
        "Onion (1kg)": 0.28,
        "Water (1.5L)": 0.25,
      },
      transport: {
        "1-way Ticket (local)": 0.12,
        "Monthly Pass": 5,
        "Taxi 1km": 0.22,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 20000,
        "Toyota Corolla": 16000,
      },
      utilities: {
        "Basic (85m² apt)": 30,
        "Mobile Plan": 4,
        "Internet (60 Mbps)": 20,
        "Fitness Club/month": 10,
      },
      housing: {
        "1BR Center": 180,
        "1BR Outside": 100,
        "3BR Center": 420,
        "3BR Outside": 235,
        "Price/m² Center": 680,
        "Price/m² Outside": 360,
      },
      salaries: {
        "Average Net Salary": 130,
        "Mortgage Interest Rate": 9.0,
      },
    },
  },
  {
    slug: "bujumbura",
    name: "Bujumbura",
    country: "Burundi",
    countryCode: "BI",
    continent: "Africa",
    costIndex: 22,
    rentIndex: 16,
    qualityOfLife: 28,
    purchasingPower: 16,
    safety: 28,
    healthcare: 22,
    climate: 68,
    trafficCommute: 16,
    population: "1.0M",
    currency: "BIF",
    avgMonthlyCost: 520,
    image: "https://images.unsplash.com/photo-1611348586754-ea3e0a748fca?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2,
        "Meal for 2 (mid-range)": 8,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1,
        "Imported Beer (0.33L)": 1.8,
        "Cappuccino": 1.2,
        "Coke/Pepsi (0.33L)": 0.4,
        "Water (0.33L)": 0.25,
      },
      markets: {
        "Milk (1L)": 0.8,
        "Bread (500g)": 0.35,
        "Rice (1kg)": 0.45,
        "Eggs (12)": 1.1,
        "Chicken (1kg)": 3,
        "Beef (1kg)": 4.5,
        "Apples (1kg)": 2,
        "Banana (1kg)": 0.25,
        "Tomato (1kg)": 0.45,
        "Potato (1kg)": 0.35,
        "Onion (1kg)": 0.3,
        "Water (1.5L)": 0.25,
      },
      transport: {
        "1-way Ticket (local)": 0.12,
        "Monthly Pass": 5,
        "Taxi 1km": 0.22,
        "Gasoline (1L)": 1.5,
        "Volkswagen Golf": 22000,
        "Toyota Corolla": 17000,
      },
      utilities: {
        "Basic (85m² apt)": 32,
        "Mobile Plan": 4,
        "Internet (60 Mbps)": 22,
        "Fitness Club/month": 12,
      },
      housing: {
        "1BR Center": 175,
        "1BR Outside": 98,
        "3BR Center": 408,
        "3BR Outside": 228,
        "Price/m² Center": 660,
        "Price/m² Outside": 348,
      },
      salaries: {
        "Average Net Salary": 120,
        "Mortgage Interest Rate": 16.0,
      },
    },
  },
  {
    slug: "malabo",
    name: "Malabo",
    country: "Equatorial Guinea",
    countryCode: "GQ",
    continent: "Africa",
    costIndex: 45,
    rentIndex: 38,
    qualityOfLife: 36,
    purchasingPower: 30,
    safety: 38,
    healthcare: 32,
    climate: 62,
    trafficCommute: 22,
    population: "0.3M",
    currency: "XAF",
    avgMonthlyCost: 1100,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 6,
        "Meal for 2 (mid-range)": 24,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 2.5,
        "Imported Beer (0.33L)": 4,
        "Cappuccino": 3,
        "Coke/Pepsi (0.33L)": 1,
        "Water (0.33L)": 0.6,
      },
      markets: {
        "Milk (1L)": 2,
        "Bread (500g)": 0.8,
        "Rice (1kg)": 1.2,
        "Eggs (12)": 2.5,
        "Chicken (1kg)": 5,
        "Beef (1kg)": 9,
        "Apples (1kg)": 4,
        "Banana (1kg)": 0.5,
        "Tomato (1kg)": 1.5,
        "Potato (1kg)": 1.2,
        "Onion (1kg)": 1,
        "Water (1.5L)": 0.6,
      },
      transport: {
        "1-way Ticket (local)": 0.4,
        "Monthly Pass": 16,
        "Taxi 1km": 0.6,
        "Gasoline (1L)": 0.7,
        "Volkswagen Golf": 32000,
        "Toyota Corolla": 25000,
      },
      utilities: {
        "Basic (85m² apt)": 90,
        "Mobile Plan": 15,
        "Internet (60 Mbps)": 50,
        "Fitness Club/month": 40,
      },
      housing: {
        "1BR Center": 650,
        "1BR Outside": 380,
        "3BR Center": 1500,
        "3BR Outside": 870,
        "Price/m² Center": 2400,
        "Price/m² Outside": 1300,
      },
      salaries: {
        "Average Net Salary": 500,
        "Mortgage Interest Rate": 12.0,
      },
    },
  },
  {
    slug: "moroni",
    name: "Moroni",
    country: "Comoros",
    countryCode: "KM",
    continent: "Africa",
    costIndex: 26,
    rentIndex: 20,
    qualityOfLife: 38,
    purchasingPower: 24,
    safety: 52,
    healthcare: 30,
    climate: 68,
    trafficCommute: 20,
    population: "0.1M",
    currency: "KMF",
    avgMonthlyCost: 620,
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 2.5,
        "Meal for 2 (mid-range)": 10,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 1.5,
        "Coke/Pepsi (0.33L)": 0.6,
        "Water (0.33L)": 0.35,
      },
      markets: {
        "Milk (1L)": 1.2,
        "Bread (500g)": 0.5,
        "Rice (1kg)": 0.5,
        "Eggs (12)": 1.5,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 6,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.3,
        "Tomato (1kg)": 0.6,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.4,
        "Water (1.5L)": 0.35,
      },
      transport: {
        "1-way Ticket (local)": 0.2,
        "Monthly Pass": 8,
        "Taxi 1km": 0.3,
        "Gasoline (1L)": 1.4,
        "Volkswagen Golf": 24000,
        "Toyota Corolla": 19000,
      },
      utilities: {
        "Basic (85m² apt)": 48,
        "Mobile Plan": 7,
        "Internet (60 Mbps)": 28,
        "Fitness Club/month": 18,
      },
      housing: {
        "1BR Center": 240,
        "1BR Outside": 135,
        "3BR Center": 560,
        "3BR Outside": 315,
        "Price/m² Center": 900,
        "Price/m² Outside": 470,
      },
      salaries: {
        "Average Net Salary": 200,
        "Mortgage Interest Rate": 12.0,
      },
    },
  },
  {
    slug: "sao-tome",
    name: "São Tomé",
    country: "São Tomé and Príncipe",
    countryCode: "ST",
    continent: "Africa",
    costIndex: 35,
    rentIndex: 28,
    qualityOfLife: 45,
    purchasingPower: 28,
    safety: 60,
    healthcare: 38,
    climate: 68,
    trafficCommute: 25,
    population: "0.1M",
    currency: "STN",
    avgMonthlyCost: 850,
    image: "https://images.unsplash.com/photo-1624394439372-fb3a72ba3b97?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 4,
        "Meal for 2 (mid-range)": 16,
        "McMeal at McDonald's": 0,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 3,
        "Cappuccino": 2,
        "Coke/Pepsi (0.33L)": 0.8,
        "Water (0.33L)": 0.5,
      },
      markets: {
        "Milk (1L)": 1.5,
        "Bread (500g)": 0.6,
        "Rice (1kg)": 0.7,
        "Eggs (12)": 1.8,
        "Chicken (1kg)": 4,
        "Beef (1kg)": 7,
        "Apples (1kg)": 3,
        "Banana (1kg)": 0.4,
        "Tomato (1kg)": 0.8,
        "Potato (1kg)": 0.6,
        "Onion (1kg)": 0.5,
        "Water (1.5L)": 0.5,
      },
      transport: {
        "1-way Ticket (local)": 0.25,
        "Monthly Pass": 10,
        "Taxi 1km": 0.4,
        "Gasoline (1L)": 1.5,
        "Volkswagen Golf": 25000,
        "Toyota Corolla": 20000,
      },
      utilities: {
        "Basic (85m² apt)": 60,
        "Mobile Plan": 10,
        "Internet (60 Mbps)": 35,
        "Fitness Club/month": 22,
      },
      housing: {
        "1BR Center": 350,
        "1BR Outside": 200,
        "3BR Center": 820,
        "3BR Outside": 460,
        "Price/m² Center": 1300,
        "Price/m² Outside": 680,
      },
      salaries: {
        "Average Net Salary": 280,
        "Mortgage Interest Rate": 14.0,
      },
    },
  },
  {
    slug: "maseru",
    name: "Maseru",
    country: "Lesotho",
    countryCode: "LS",
    continent: "Africa",
    costIndex: 26,
    rentIndex: 20,
    qualityOfLife: 38,
    purchasingPower: 26,
    safety: 38,
    healthcare: 32,
    climate: 60,
    trafficCommute: 22,
    population: "0.3M",
    currency: "LSL",
    avgMonthlyCost: 620,
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 3,
        "Meal for 2 (mid-range)": 11,
        "McMeal at McDonald's": 4,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 2,
        "Coke/Pepsi (0.33L)": 0.7,
        "Water (0.33L)": 0.4,
      },
      markets: {
        "Milk (1L)": 0.9,
        "Bread (500g)": 0.6,
        "Rice (1kg)": 0.8,
        "Eggs (12)": 1.6,
        "Chicken (1kg)": 3.5,
        "Beef (1kg)": 5.5,
        "Apples (1kg)": 1.5,
        "Banana (1kg)": 0.6,
        "Tomato (1kg)": 0.7,
        "Potato (1kg)": 0.5,
        "Onion (1kg)": 0.45,
        "Water (1.5L)": 0.4,
      },
      transport: {
        "1-way Ticket (local)": 0.3,
        "Monthly Pass": 12,
        "Taxi 1km": 0.4,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 26000,
        "Toyota Corolla": 21000,
      },
      utilities: {
        "Basic (85m² apt)": 55,
        "Mobile Plan": 8,
        "Internet (60 Mbps)": 32,
        "Fitness Club/month": 20,
      },
      housing: {
        "1BR Center": 260,
        "1BR Outside": 145,
        "3BR Center": 605,
        "3BR Outside": 340,
        "Price/m² Center": 980,
        "Price/m² Outside": 515,
      },
      salaries: {
        "Average Net Salary": 280,
        "Mortgage Interest Rate": 12.5,
      },
    },
  },
  {
    slug: "mbabane",
    name: "Mbabane",
    country: "Eswatini",
    countryCode: "SZ",
    continent: "Africa",
    costIndex: 28,
    rentIndex: 22,
    qualityOfLife: 40,
    purchasingPower: 28,
    safety: 40,
    healthcare: 34,
    climate: 68,
    trafficCommute: 24,
    population: "0.1M",
    currency: "SZL",
    avgMonthlyCost: 700,
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    categories: {
      restaurants: {
        "Meal (inexpensive)": 3.5,
        "Meal for 2 (mid-range)": 14,
        "McMeal at McDonald's": 4,
        "Domestic Beer (0.5L)": 1.5,
        "Imported Beer (0.33L)": 2.5,
        "Cappuccino": 2.2,
        "Coke/Pepsi (0.33L)": 0.8,
        "Water (0.33L)": 0.45,
      },
      markets: {
        "Milk (1L)": 1,
        "Bread (500g)": 0.7,
        "Rice (1kg)": 0.9,
        "Eggs (12)": 1.8,
        "Chicken (1kg)": 3.8,
        "Beef (1kg)": 6,
        "Apples (1kg)": 1.6,
        "Banana (1kg)": 0.6,
        "Tomato (1kg)": 0.8,
        "Potato (1kg)": 0.6,
        "Onion (1kg)": 0.5,
        "Water (1.5L)": 0.45,
      },
      transport: {
        "1-way Ticket (local)": 0.35,
        "Monthly Pass": 14,
        "Taxi 1km": 0.45,
        "Gasoline (1L)": 1.3,
        "Volkswagen Golf": 26000,
        "Toyota Corolla": 21000,
      },
      utilities: {
        "Basic (85m² apt)": 60,
        "Mobile Plan": 9,
        "Internet (60 Mbps)": 34,
        "Fitness Club/month": 22,
      },
      housing: {
        "1BR Center": 280,
        "1BR Outside": 158,
        "3BR Center": 655,
        "3BR Outside": 368,
        "Price/m² Center": 1060,
        "Price/m² Outside": 558,
      },
      salaries: {
        "Average Net Salary": 320,
        "Mortgage Interest Rate": 11.5,
      },
    },
  },
];

export const getCityBySlug4 = (slug) => cities4.find((c) => c.slug === slug);